INSERT INTO REVIEW(REVIEW_NO, RES_NO, USER_NO, BOOK_NO, REVIEW_CONTENT, STAR, CREATE_DATE, STATUS, GOOD, COUNT)
            VALUES(SEQ_RVNO.NEXTVAL, 1200, 1, 1, '진짜 맛있다!', 5, SYSDATE, 'Y', 'Y', 0);

INSERT INTO REVIEW(REVIEW_NO, RES_NO, USER_NO, BOOK_NO, REVIEW_CONTENT, STAR, CREATE_DATE, STATUS, GOOD, COUNT)
            VALUES(SEQ_RVNO.NEXTVAL, 1200, 2, 2, '진짜 별로!', 1, SYSDATE, 'Y', 'Y', 0);

INSERT INTO REVIEW(REVIEW_NO, RES_NO, USER_NO, BOOK_NO, REVIEW_CONTENT, STAR, CREATE_DATE, STATUS, GOOD, COUNT)
            VALUES(SEQ_RVNO.NEXTVAL, 1200, 3, 3, '그냥 저냥!', 3, SYSDATE, 'Y', 'Y', 0);

INSERT INTO REVIEW(REVIEW_NO, RES_NO, USER_NO, BOOK_NO, REVIEW_CONTENT, STAR, CREATE_DATE, STATUS, GOOD, COUNT)
            VALUES(SEQ_RVNO.NEXTVAL, 1200, 1, 4, '이게 맛 없으면 맛알못', 4, SYSDATE, 'Y', 'Y', 0);

INSERT INTO REVIEW(REVIEW_NO, RES_NO, USER_NO, BOOK_NO, REVIEW_CONTENT, STAR, CREATE_DATE, STATUS, GOOD, COUNT)
            VALUES(SEQ_RVNO.NEXTVAL, 1200, 3, 5, '엄청 맛있진 않지만 가성비가 괜찮네', 4, SYSDATE, 'Y', 'Y', 0);
            
            
COMMIT;