SELECT DISTINCT A.USER_NO, USER_ID, USER_NAME, USER_PHONE, USER_EMAIL , GENDER,
        (NVL((SELECT COUNT(B.USER_NO)
          FROM BOOK B
          JOIN TB_USER U ON (U.USER_NO = B.USER_NO)
          GROUP BY B.USER_NO, U.USER_NO
        HAVING B.USER_NO = A.USER_NO) , 0)) "예약횟수",
        (NVL((SELECT COUNT(R.USER_NO)
          FROM REVIEW R
          JOIN TB_USER F ON (R.USER_NO = F.USER_NO)
          GROUP BY R.USER_NO, F.USER_NO
        HAVING R.USER_NO = A.USER_NO), 0)) "리뷰 갯수"
 FROM TB_USER A
 JOIN BOOK C ON (A.USER_NO = C.USER_NO)
 JOIN REVIEW H ON (C.USER_NO = H.USER_NO)
WHERE NOT A.STATUS = 'A'
ORDER
   BY USER_NO ASC;